app_test/urls.py
from django.urls import path
from app_test.views import *

app_name = 'app_test'

urlpatterns = [
    path('tests/', tests, name='tests'),
    path('<int:test_id>/', display_test, name='display_test'),
    path('<int:test_id>/questions/<int:question_id>', display_question, name='display_question'),
    path('<int:test_id>/questions/<int:question_id>/grade/', grade_question, name='grade_question'),
    path('results/<int:test_id>/', test_results, name='test_results'), 
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('administrator/', admin.site.urls),
    path('', include('app_blog.urls')),
    path('', include('app_task.urls')),
    path('', include('app_test.urls')),
    path('', include('app_users.urls')),
    path('captcha/', include('captcha.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/account.html
{% extends "base.html" %}

{% load static %}
{% block title %}Мой профиль{% endblock title %}
{% block content%}
<style>
    body {
        background: linear-gradient(to right bottom, var(--bg-color), var(--main-color));
    }
</style>
<div class="profile-container">
    <div class="profile">
        <div class="profile-header">
            <img src="{{ profile.image.url }}" alt="profile" class="profile-img" />
        </div>

        <div class="profile-menu">
            <a href="{% url 'account' %}" class="profile-menu-link profile-menu-link-active"><i class="fa-solid fa-circle-user profile-menu-icon"></i>Мой профиль</a>
            <a href="{% url 'edit-account' %}" class="profile-menu-link"><i class="fa-solid fa-gear profile-menu-icon"></i>Редактировать профиль</a>
            <a href="{% url 'logoutUser' %}" class="profile-menu-link"><i class="fa-solid fa-bracket profile-menu-icon"></i>Выйти из аккаунта</a>
        </div>
    </div>

    <div class="account">
        <div class="account-header">
            <h1 class="account-title">Мой <span>профиль</span></h1>
        </div>
        <div class="account-info">
            <div class="input-container">
                <label>Имя</label>
                <p>{{ profile.first_name }}</p>
            </div>
            <div class="input-container">
                <label>Фамилия</label>
                <p>{{ profile.last_name }}</p>
            </div>
        </div>

        <div class="account-info">
            <div class="input-container">
                <label>Email</label>
                <p>{{ profile.email }}</p>
            </div>
            <div class="input-container">
                <label>Город</label>
                <p>{{ profile.city }}</p>
            </div>
        </div>

        <div class="account-info">
            <div class="input-container">
                <label>Пара слов о себе</label>
                <div class="readonly-text">{{ profile.about }}</div>
            </div>
        </div>
        <div class="account-info">
            <div class="input-container">
                <label>Баллов</label>
                <p>{{ profile.points }}</p>
            </div>
            <div class="input-container">
                <label>Уровень</label>
                <p>{{ profile.level }}</p>
            </div>
        </div>
    </div>
</div>
<div class="popup" id="popup">
    <div id="popup-messages">
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    </div>
    <button type="button" onclick="closePopup()">Закрыть</button>
</div>
{% endblock %}

{% block footer %}{% endblock footer %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Cybersecurity School{% endblock title %}</title>
    <link rel="icon" href="{% static "img/favicon.ico" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://kit.fontawesome.com/64d58efce2.js" crossorigin="anonymous"></script>
    {% block style %}{% endblock style %}
</head>
<body>
    {% block header %}
    {% if user.is_authenticated %}
    <header class="header">
        <a href="{% url 'landing' %}" class="logo">CyberSecurity <span>School</span></a>
        <i class='bx bx-menu' id="menu-icon"></i>
        <nav class="navbar">
            {% comment %} <a href="/events">Event</a> {% endcomment %}
            <a href="{% url 'articles' %}">Статьи</a>
            <a href="/tests">Тесты</a>
            <a href="/tasks">Задания</a>
            <a href="/leaderboard">Рейтинг</a>
            <a href="/account">Мой профиль</a>
            <a href="/logoutUser">Выйти</a>
        </nav>
    </header>
    {% else %}
    <header class="header">
        <a href="{% url 'landing' %}" class="logo">CyberSecurity <span>School</span></a>
        <i class='bx bx-menu' id="menu-icon"></i>
        <nav class="navbar">
            <a href="{% url 'articles' %}">Статьи</a>
            <a href="{% url 'leaderboardUsers' %}">Рейтинг</a>
            <a href="{% url 'login' %}">Вход</a>
        </nav>
    </header>
    {% endif %}
    {% endblock header %}
    {% block content %}{% endblock %}
    {% block footer %}
    <footer class="footer">
        
        <ul class="list">
            <li>
                <a href="https://new.college.asu.ru/pk/obespechenie-informacionnoj-bezopasnosti-avtomatizirovannyh-sistem/">Колледж</a>
            </li>
            <li>
                <a href="https://phys.asu.ru/%D0%B0%D0%B1%D0%B8%D1%82%D1%83%D1%80%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC/%D0%B1%D0%B0%D0%BA%D0%B0%D0%BB%D0%B0%D0%B2%D1%80%D0%B8%D0%B0%D1%82/%D0%BD%D0%B0%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D0%B0%D1%8F-%D0%B1%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81/%D0%BF%D0%BE%D0%B4%D0%B3%D0%BE%D1%82%D0%BE%D0%B2%D0%BA%D0%B0-%D1%81%D0%BF%D0%B5%D1%86%D0%B8%D0%B0%D0%BB%D0%B8%D1%81%D1%82%D0%BE%D0%B2-%D0%B2-%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D0%B8-%D0%B8%D0%BD/">Бакалавриат</a>
            </li>
            <li>
                <a href="https://phys.asu.ru/%D0%B0%D0%B1%D0%B8%D1%82%D1%83%D1%80%D0%B8%D0%B5%D0%BD%D1%82%D0%B0%D0%BC/%D0%BC%D0%B0%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B0%D1%82%D1%83%D1%80%D0%B0/%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D0%B0%D1%8F-%D0%B1%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D0%B1%D0%B0%D0%BD%D0%BA%D0%BE%D0%B2%D1%81/">Магистратура</a>
            </li>
            <li>
                <a href="https://www.asu.ru/education/aspir_admiss/">Аспирантура</a>
            </li>
            <li>
                <a href="https://phys.asu.ru/%D1%83%D1%87%D0%B5%D0%B1%D0%BD%D1%8B%D0%B9-%D1%86%D0%B5%D0%BD%D1%82%D1%80-%D0%B4%D0%BF%D0%BE-%D0%B8%D1%86%D1%82%D1%8D%D1%84/">ДПО</a>
            </li>
        </ul>
        <p class="copyright">© CyberSecurity School | All Rights Reserved | Created by <a href="https://vk.com/d.fedoseenko" style='color:white;'>Danil Fedoseenko</a></p>
    </footer>
    {% endblock footer%}
    <script src="{% static "js/script-landing.js" %}"></script>
</body>
</html>

templates/display.html
{% extends "base.html" %}

{% load static %}
{% block title %}Тест{% endblock title %}
{% block content %}
<style>
    body{
        height: 100%;
    }
    .main-wrap{
        display: flex;
        width: 100%;
        justify-content: center;
        align-items: center; /* выравнивание по верхнему краю контейнера */
        height: 100%;
        margin-top: 8rem; /* отступ сверху */
        box-sizing: border-box; /* включение отступов в расчёт высоты */
        margin-bottom: 4rem;
        height: 75vh;
    }
    .form_radio_btn, .form_radio_btn label{
        max-width: 800px;
        width: 100%;
    }
</style>
<div class="main-wrap">
<div class="mainer-container">
    <div class="question">
        <h2>Вопрос {{ current_index }} из {{ number }}</h2>
        <p>{{ question.name }}</p>
    </div>
    <form id="question-form" action="{% url 'app_test:grade_question' test.id question.id %}" method="post">
        {% csrf_token %}
        {% if question.qtype == 'single' %}
            <div class="question-exp">
                <p>Только один ответ здесь - правильный</p>
            </div>
            {% for answer in question.answer_set.all %}
                <div class="answer-options">
                    <div class="form_radio_btn">
                        <input type="radio" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}"/>
                        <label for="answer{{ forloop.counter }}">{{ answer.name | safe }}</label>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="question-exp">
                <p>Здесь несколько правильных ответов</p>
            </div>
            {% for answer in question.answer_set.all %}
            <div class="form_radio_btn">
                <input type="checkbox" name="answer" id="answer{{ forloop.counter }}" value="{{ answer.id }}"/>
                <label for="answer{{ forloop.counter }}">{{ answer.name | safe }}</label>
            </div>
            {% endfor %}
        {% endif %}
        <button type="submit" class="return_test_button">Ответить</button>
        </form>
            <div id="question-feedback" class="question-explanation"></div>
            <div id="next-question-container" class="next-question">
                {% if next_question %}
                    <a class="return_test_button" href="{% url 'app_test:display_question' test.id next_question.id %}">Следующий вопрос</a>
                {% else %}
                    <a class="test_button" href="{% url 'app_test:test_results' test.id %}">Посмотреть результаты</a>
                {% endif %}
            </div>
            
</div>
</div>
<script>
    const form = document.getElementById("question-form");
    form.addEventListener("submit", (e) => {
        e.preventDefault();
        fetch(form.action, {
            method: 'POST',
            body: new FormData(form)
        })
        .then(response => response.text())
        .then(text => {
            document.getElementById("question-feedback").innerHTML = text;
            document.getElementById("next-question-container").style.display = 'block'; // Показать кнопки после ответа
        })
        .catch(error => console.error('Error:', error));
    });
</script>
{% endblock %}

templates/edit_account.html
{% extends "base.html" %}

{% load static %}
{% block title %}Редактирование профиля{% endblock title %}
{% block content %}
<style>
    body {
        background: linear-gradient(to right bottom, var(--bg-color), var(--main-color));
    }
</style>
<div class="profile-container">
    <div class="profile">
        <div class="profile-header">
        </div>

        <div class="profile-menu">
            <a href="{% url 'account' %}" class="profile-menu-link"><i class="fa-solid fa-circle-user profile-menu-icon"></i>Мой профиль</a>
            <a href="{% url 'edit-account' %}" class="profile-menu-link profile-menu-link-active"><i class="fa-solid fa-gear profile-menu-icon"></i>Редактировать профиль</a>
            <a href="{% url 'logoutUser' %}" class="profile-menu-link"><i class="fa-solid fa-bracket profile-menu-icon"></i>Выйти из аккаунта</a>
        </div>
    </div>

    <form method="POST" action="{% url 'edit-account' %}" class="account" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="account-header">
            <h1 class="account-title">Редактирование <span>профиля</span></h1>
            <div class="button-profile-container">  
                <button type="submit" class="button-profile-save">Сохранить изменения</button>
            </div>
        </div>
        
        {% for field in form %}
        <div class="account-edit">
            <div class="input-container">
                <label for={{ field.name }}>{{ field.label }}</label>
                {{ field }}
            </div>
        </div>
        {% endfor %}
        {% for error in field.errors %}<p>{{ error }}</p>
        {% endfor %}
        
    </form>
</div>
{% endblock  %}

templates/event_rating.html
{% extends "base.html" %}

{% load static %}
{% block title %}Рейтинговая таблица{% endblock title %}
{% block content %}
<style>
    body {
        background: linear-gradient(to right bottom, var(--bg-color), var(--main-color));
    }
</style>  
    <div class="test-container">
        <h1 class="rating-heading">Рейтинги соревнования</h1>
            <div class="rating-container">
                <table>
                    <thead>
                    <tr>
                        <th scope="col">Sr:No</th>
                        <th scope="col">Username</th>
                        <th scope="col">Points</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users %}
                    <tr>
                        <td scope="row" data-label="Sr:No">{{ forloop.counter }}</td>
                        <td data-label="Username"><a href="{% url 'user-profile' user.username %}">{{ user.username }}</a></td>
                        <td data-label="Points">{{ user.event_points }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
{% endblock %}

{% block footer %}{% endblock footer %}

templates/login.html
{% extends "base.html" %}

{% load static %}
{% block title %}Авторизация{% endblock title %}
{% block content %}
<style>
    body {
        background: linear-gradient(to right bottom, var(--bg-color), var(--main-color));
    }
</style>
<div class="wrappper">   
    <div class="form-box">
        <div class="login-container">
            <div class="top">
                <div class="title">Вход в аккаунт</div>
            </div>
            <form action="{% url 'login' %}" method="POST">
                {% csrf_token %}
            <div class="input-box">
                {{ form.username }}
                <i class="bx bx-user"></i>
            </div>
            <div class="input-box">
                {{ form.password }}
                <i class="bx bx-lock-alt"></i>
            </div>
            <div class="input-box">
                
                {{ form.captcha }}
                <i class="bx bx-lock-alt"></i>
            </div>
            <div class="input-box">
                <input type="submit" class="submit" value="Войти">
            </div>
            <div class="two-col">
                <div class="two">
                    <label> <a href="{% url 'register' %}">Регистрация</a></label>
                </div>
                <div class="two">
                    <label><a href="{% url 'password_reset' %}">Забыли пароль?</a></label>
                </div>
            </div>
            </form>
        </div>
    </div>
    <div class="popup" id="popup">
        <div id="popup-messages">
            {% for message in messages %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
        <button type="button" onclick="closePopup()">Закрыть</button>
    </div>
</div> 

<script>
    let popup = document.getElementById("popup");

    function openPopup() {
        popup.classList.add("open-popup");
    }

    function closePopup() {
        popup.classList.remove("open-popup");
    }

    document.addEventListener("DOMContentLoaded", function() {
        {% if messages %}
            openPopup();
        {% endif %}
    });
</script>

{% endblock %}

{% block footer %}{% endblock footer %}

templates/partial.html
{% if error_message %}
    <span>{{ error_message }}</span>
{% elif is_correct %}
    <span>Правильно.</span>
    <span>{{ question.explanation }}</span>
{% elif is_correct == None %}
    <span>Не выбран вариант ответа. Не забудьте ответить позже!</span>
{% else %}
    {% if correct_answer|length > 1 %}
        <div>
            Частично верно! Правильные ответы:
            <ul>
                {% for answer in correct_answer %}<li>{{ answer }}</li>{% endfor %}
            </ul>
        </div>
    {% else %}
        <span>Неверно! Правильный ответ: {{ correct_answer }}</span>
    {% endif %}
    <span>{{ question.explanation }}</span>
{% endif %}

templates/rating.html
{% extends "base.html" %}

{% load static %}
{% block title %}Рейтинговая таблица{% endblock title %}
{% block content %}
<style>
    body {
        background: linear-gradient(to right bottom, var(--bg-color), var(--main-color));
    }
</style>  
    <div class="test-container">
        <h1 class="rating-heading">Рейтинговая таблица</h1>
            <div class="rating-container">
                <table>
                    <thead>
                    <tr>
                        <th scope="col">Sr:No</th>
                        <th scope="col">Username</th>
                        <th scope="col">Points</th>
                        <th scope="col">Level</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for user in users %}
                    <tr>
                        <td scope="row" data-label="Sr:No">{{ forloop.counter }}</td>
                        <td data-label="Username"><a href="{% url 'user-profile' user.username %}">{{ user.username }}</a></td>
                        <td data-label="Points">{{ user.points }}</td>
                        <td data-label="Level">{{ user.level }}</td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
{% endblock %}

{% block footer %}{% endblock footer %}

templates/tasks.html
{% extends "base.html" %}

{% load static %}
{% block title %}Задания{% endblock title %}
{% block content %}
<style>
    body {
        background: linear-gradient(to right bottom, var(--bg-color), var(--main-color));
    }
</style>
<h2 class="tasks-heading">Задания</h2>
<div class="tasks-container">
    {% for task in tasks %}
    <div class="tasks-box">
        <img src="{{ task.title_image.url }}" alt="task Image" class="tasks-img">
        <div class="tasks-info">
            <h4>{{ task.task_title }}</h4>
            <h5>Сложность: {{ task.difficulty}}</h5>
            <h5>Тип задания: {{ task.type_task }}</h5>
            <p>{{ task.task_description }}</p>
        </div>
        <div class="tasks-details">
            <div class="tasks-points">{{ task.points }} points</div>
            <a href="{% url 'view_ctfTask' task.id %}" class="tasks-btn">Перейти</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock  %}

templates/tests.html
{% extends "base.html" %}

{% load static %}
{% block title %}Тесты{% endblock title %}
{% block content %}
<style>
    body {
        background: linear-gradient(to right bottom, var(--bg-color), var(--main-color));
    }
</style>
<div class="test-container">
    <h2 class="test-heading">Тесты</h2>
    <div class="card-container">
        {% for test in tests %}
        <div class="card">
            <div class="card-content">
                <h3>{{ test.name }}</h3>
                <p>{{ test.test_description }}</p>
                <a href="{% url 'app_test:display_test' test.id %}" class="card-content-button">Пройти тест</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>    
{% endblock  %}

templates/user_password_reset.html
{% extends 'base.html' %}

{% block title %}Запрос на сброс пароля{% endblock title %}

{% block content %}
<style>
    body {
        background: linear-gradient(to right bottom, var(--bg-color), var(--main-color));
    }
</style>
<div class="set-new-password">
    <h3 class="password-heading">Запрос на сброс пароля</h3>
        <div class="container-reset">
            <form method="post">
                {% csrf_token %}
                <h4 class="text-email-password">Введите Email, который был использован при регистрации, чтобы мы могли отправить ссылку на восстановление пароля</h4>
                {{ form.as_p }}
                <button type="submit" class="button-password">Отправить запрос</button>
            </form>
        </div>
</div>
{% endblock %}

{% block footer %}{% endblock footer %}

templates/user_password_set_new.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Установка нового пароля{% endblock title %}
{% block content %}
<style>
    body {
        background: linear-gradient(to right bottom, var(--bg-color), var(--main-color));
    }
</style>
<div class="set-new-password">
    <h3 class="password-heading">Установка нового пароля</h3>
        <div class="container-set">
            <form method="post">
                {% csrf_token %}
                <h4 class="text-email-password">Создайте новый пароль для своего аккаунта, который отвечает требованиям информационной безопасности</h4>
                <h5 class="password-set">
                    <p>1. Минимальная длина пароля: 8 символов</p>
                    <p>2. Нужны цифры, а также буквы латинского алфавита разных регистров</p>
                    <p>3. Необходимо наличие спецсимволов</p>
                </h5>
                {{ form.as_p }}
                <button type="submit" class="button-password">Установить пароль</button>
            </form>
        </div>
</div>
{% endblock %}

{% block footer %}{% endblock footer %}

templates/view_event.html
{% extends "base.html" %}

{% load static %}
{% block title %}Задание{% endblock title %}
{% block style %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
{% endblock style %}
{% block content %}
<style>
    body{
        background: linear-gradient(to right bottom, var(--bg-color), var(--main-color));
    }
    .main-container{
        height: 71vh;
        margin-top: 15rem;
        margin-bottom: 5rem;
    }
    .task-materials a{
        font-size: 2rem;
        color: var(--main-color);
    }

    @media(max-width:991px){
        .footer{
            margin-top: 100px;
        }
    }
</style>
<div class="main-container">
    <div class="task-container">
        <a href="{% url 'ctfEvents' %}" class="return-button"><i class="fas fa-arrow-left"></i> Вернуться назад</a>
        <div class="task-header">
            <div>
                <h1>{{ task.task_title }}</h1>
                <p>Уровень: <span class="difficulty">{{ task.difficulty }}</span></p>
            </div>
            <div class="task-reward">
                <p>Награда за выполнение: <span>{{ task.points }} очков</span></p>
                <p>Тип задания: <span>{{ task.type_task }}</span></p>
            </div>
        </div>
        <div class="task-description">
            <p>{{ task.task_text }}</p>
            
        </div>
        <div class="task-materials">
            {% if task.material_file %}
            <p>Materials: <a href="{{ task.material_file.url }}" download>здесь</a></p>
            {% endif %}
        </div>
        <hr>
        <form action="{% url 'view_ctfTask' task.id %}" method="post">
            {% csrf_token %}
            <div class="task-answer">
            <label for="answer">Ответ</label>
            <input type="text" id="user_answer" name="user_answer" placeholder="Enter your key" required>
            </div>
        <button type="submit" class="submit-button">Отправить</button>
        </form>
        {% if already_answered %}
        <p>Вы уже успешно прошли это задание и получили за него баллы.</p>
        {% endif %}

        {% if is_correct is not None %}
        <div class="task-explanation">
            {% if is_correct %}
                <p class="correct">Правильно! Вы получили {{ task.points }} очков.</p>
            {% else %}
                <p class="incorrect">Неправильно! Попробуйте снова.</p>
            {% endif %}
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/view_task.html
{% extends "base.html" %}

{% load static %}
{% block title %}{{ task.task_title }}{% endblock title %}
{% block style %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
{% endblock style %}
{% block content %}
<style>
    body{
        background: linear-gradient(to right bottom, var(--bg-color), var(--main-color));
        height: 0%;
    }
    .task-materials a{
        font-size: 2rem;
        color: var(--main-color);
    }

    @media(max-width:991px){
        .footer{
            margin-top: 100px;
        }
    }
</style>
<div class="main-container">
    <div class="task-container">
        <a href="{% url 'ctfTasks' %}" class="return-button"><i class="fas fa-arrow-left"></i> Вернуться назад</a>
        <div class="task-header">
            <div>
                <h1>{{ task.task_title }}</h1>
                <p>Уровень: <span class="difficulty">{{ task.difficulty }}</span></p>
            </div>
            <div class="task-reward">
                <p>Награда за выполнение: <span>{{ task.points }} очков</span></p>
                <p>Тип задания: <span>{{ task.type_task }}</span></p>
            </div>
        </div>
        <div class="task-description">
            <p>{{ task.task_text }}</p>
            
        </div>
        <div class="task-materials">
            {% if task.material_file %}
            <p>Materials: <a href="{{ task.material_file.url }}" download>здесь</a></p>
            {% endif %}
        </div>
        <hr>
        <form action="{% url 'view_ctfTask' task.id %}" method="post">
            {% csrf_token %}
            <div class="task-answer">
            <label for="answer">Ответ</label>
            <input type="text" id="user_answer" name="user_answer" placeholder="Enter your key" required>
            </div>
        <button type="submit" class="submit-button">Отправить</button>
        </form>
        {% if already_answered %}
        <p>Вы уже успешно прошли это задание и получили за него баллы.</p>
        {% endif %}

        {% if is_correct is not None %}
        <div class="task-explanation">
            {% if is_correct %}
                <p class="correct">Правильно! Вы получили {{ task.points }} очков.</p>
            {% else %}
                <p class="incorrect">Неправильно! Попробуйте снова.</p>
            {% endif %}
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}